<?php
/**
 * Product:     Recurring Purchase Assistant
 * Package:     Aitoc_Aitproductslists_1.0.4_1.0.0_520324
 * Purchase ID: kFkbuT14FmWJApKR3QE9iykvMGpr0gLJWvjTDjDtbI
 * Generated:   2013-03-08 08:15:21
 * File path:   app/design/frontend/base/default/template/aitproductslists/catalog/product/jsadd.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<script type="text/javascript">
//<![CDATA[
productAddToCartForm.addToList = function(button, url) {
    
	
//	var aitForm = new VarienForm('product_addtocart_form', true);
	
	
	if (this.validator.validate()) {
        var form = this.form;
	    var oldUrl = form.action;

        if (url) {
           form.action = url;
        }
        var e = null;
        try {
            this.form.submit();
        } catch (e) {
        }
        this.form.action = oldUrl;
        if (e) {
            throw e;
        }

        if (button && button != 'undefined') {
            button.disabled = true;
        }
    }
}.bind(productAddToCartForm);

 productAddToCartForm.submit = function(button, url) {
    
            $('add_list_input').className='input-text';
            if($('existing_lists') !== null)
            {
                $('existing_lists').className='select';
            }
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);
//]]>
</script>