<?php
/**
 * Product:     Recurring Purchase Assistant
 * Package:     Aitoc_Aitproductslists_1.0.4_1.0.0_520324
 * Purchase ID: kFkbuT14FmWJApKR3QE9iykvMGpr0gLJWvjTDjDtbI
 * Generated:   2013-03-08 08:15:21
 * File path:   app/design/adminhtml/default/default/template/aitproductslists/list/js.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<script type="text/javascript">
    Event.observe(window, 'load',  function() {
        productConfigure.addListType('product_to_add', {
            urlFetch: '<?php echo $this->getUrl('*/aitppl_products/configureProductToAdd') ?>'
        });
        productConfigure.addListType('quote_items', {
            urlFetch: '<?php echo $this->getUrl('*/aitppl_products/configureQuoteItems') ?>'
        });
    });
</script>